// gameData.ts
import type { Level } from "@shared/schema";
import type { QuestionType } from "./questionType"; // or define your types if needed

export const LEVELS: Level[] = [
  {
    id: "1.01",
    number: "1.01",
    title: "Simplifying & Distributive Property",
    description: "Learn to expand expressions and combine like terms",
    type: "lesson",
    xpReward: 50,
    badge: "distributive-dominator",
    // Instead of manually writing questions, define what type to generate and how many
    questionType: "simplifyOrDistribute",
    questionCount: 12,
  },
  {
    id: "1.02",
    number: "1.02",
    title: "Solving Linear Equations",
    description: "Solve multi-step equations with variables on both sides",
    type: "lesson",
    xpReward: 60,
    questionType: "linearEquation",
    questionCount: 12,
  },
  {
    id: "1.03",
    number: "1.03",
    title: "Equations with Fractions",
    description: "Clear denominators and solve equations with fractions",
    type: "lesson",
    xpReward: 70,
    badge: "fraction-fragger",
    questionType: "fractionEquation",
    questionCount: 12,
  },
  {
    id: "1.04",
    number: "1.04",
    title: "Graphing Linear Equations",
    description: "Identify slope, y-intercept, and match graphs to equations",
    type: "lesson",
    xpReward: 70,
    badge: "graphing-guru",
    questionType: "graphEquation",
    questionCount: 12,
  },
  {
    id: "1.05",
    number: "1.05",
    title: "Standard Form",
    description: "Convert between forms and find intercepts",
    type: "lesson",
    xpReward: 70,
    badge: "slope-master",
    questionType: "standardForm",
    questionCount: 12,
  },
  {
    id: "1.06",
    number: "1.06",
    title: "Parallel & Perpendicular Lines",
    description: "Understand relationship between slopes of parallel and perpendicular lines",
    type: "lesson",
    xpReward: 80,
    badge: "parallel-pro",
    questionType: "parallelPerpendicular",
    questionCount: 12,
  },
  {
    id: "1.07",
    number: "1.07",
    title: "Equation Given Two Points",
    description: "Find the equation of a line given two points",
    type: "lesson",
    xpReward: 80,
    badge: "two-point-titan",
    questionType: "twoPointLine",
    questionCount: 12,
  },
  {
    id: "1.08",
    number: "1.08",
    title: "Word Problems with Lines",
    description: "Apply linear equations to real-world problems",
    type: "lesson",
    xpReward: 80,
    questionType: "wordProblem",
    questionCount: 12,
  },
  {
    id: "1.09",
    number: "1.09",
    title: "Substitution Method",
    description: "Solve systems of equations using substitution",
    type: "lesson",
    xpReward: 90,
    badge: "substitution-samurai",
    questionType: "substitution",
    questionCount: 12,
  },
  {
    id: "1.10",
    number: "1.10",
    title: "Elimination & Matrices Intro",
    description: "Solve systems using elimination and intro to matrices",
    type: "lesson",
    xpReward: 100,
    badge: "elimination-elite",
    questionType: "eliminationMatrix",
    questionCount: 12,
  },
];
