import type { Level, Question } from "@shared/schema";

function generateId(): string {
  return Math.random().toString(36).substring(2, 9);
}

export const LEVELS: Level[] = [
  {
    id: "1.01",
    number: "1.01",
    title: "Simplifying & Distributive Property",
    description: "Learn to expand expressions and combine like terms",
    type: "lesson",
    xpReward: 50,
    badge: "distributive-dominator",
    questions: [
      { id: generateId(), type: "mcq", question: "Expand: 3(2x - 4)", options: ["6x - 12", "6x - 4", "5x - 7", "6x + 12"], correctAnswer: "6x - 12", hint: "Multiply 3 by each term inside" },
      { id: generateId(), type: "mcq", question: "Simplify: 5x + 3 - 2x + 8", options: ["3x + 11", "7x + 11", "3x - 5", "7x - 5"], correctAnswer: "3x + 11", hint: "Combine like terms: x terms and constants" },
      { id: generateId(), type: "mcq", question: "Expand: -2(4x + 5)", options: ["-8x - 10", "-8x + 10", "8x - 10", "-6x - 7"], correctAnswer: "-8x - 10", hint: "Multiply -2 by each term" },
      { id: generateId(), type: "input", question: "Expand and simplify: 2(x + 3) + 4x", correctAnswer: "6x + 6", hint: "First expand, then combine" },
      { id: generateId(), type: "mcq", question: "Simplify: 7x - 3 + 2x - 5", options: ["9x - 8", "5x + 2", "9x + 8", "5x - 8"], correctAnswer: "9x - 8", hint: "Add the x terms, add the constants" },
      { id: generateId(), type: "mcq", question: "Expand: 5(x - 2)", options: ["5x - 10", "5x - 2", "5x + 10", "x - 10"], correctAnswer: "5x - 10", hint: "5 times x and 5 times -2" },
      { id: generateId(), type: "input", question: "Expand: 4(3x + 1)", correctAnswer: "12x + 4", hint: "Multiply 4 by each term" },
      { id: generateId(), type: "mcq", question: "Simplify: 3x + 2y - x + 5y", options: ["2x + 7y", "4x + 7y", "2x - 3y", "4x + 3y"], correctAnswer: "2x + 7y", hint: "Combine x terms and y terms separately" },
      { id: generateId(), type: "mcq", question: "Expand: -3(2x - 7)", options: ["-6x + 21", "-6x - 21", "6x + 21", "-6x - 7"], correctAnswer: "-6x + 21", hint: "Remember: negative times negative is positive" },
      { id: generateId(), type: "input", question: "Expand and simplify: 3(x + 2) - 2(x - 1)", correctAnswer: "x + 8", hint: "Expand both, then combine like terms" },
      { id: generateId(), type: "mcq", question: "Simplify: 8 - 2x + 4x - 3", options: ["2x + 5", "6x + 5", "-2x + 5", "2x + 11"], correctAnswer: "2x + 5", hint: "Combine x terms and constants" },
      { id: generateId(), type: "mcq", question: "Expand: 6(x + 4)", options: ["6x + 24", "6x + 4", "10x", "6x - 24"], correctAnswer: "6x + 24", hint: "Multiply 6 by each term inside" },
    ],
  },
  {
    id: "1.02",
    number: "1.02",
    title: "Solving Linear Equations",
    description: "Solve multi-step equations with variables on both sides",
    type: "lesson",
    xpReward: 60,
    questions: [
      { id: generateId(), type: "input", question: "Solve: 3x + 7 = 22", correctAnswer: "5", hint: "Subtract 7, then divide by 3" },
      { id: generateId(), type: "mcq", question: "Solve: 2x - 5 = 9", options: ["x = 7", "x = 2", "x = 14", "x = -7"], correctAnswer: "x = 7", hint: "Add 5 to both sides, then divide by 2" },
      { id: generateId(), type: "input", question: "Solve: 4x - 3 = 2x + 7", correctAnswer: "5", hint: "Get all x terms on one side" },
      { id: generateId(), type: "mcq", question: "Solve: 5x + 2 = 3x + 10", options: ["x = 4", "x = 6", "x = 2", "x = -4"], correctAnswer: "x = 4", hint: "Subtract 3x from both sides first" },
      { id: generateId(), type: "input", question: "Solve: 6x - 4 = 20", correctAnswer: "4", hint: "Add 4, then divide by 6" },
      { id: generateId(), type: "mcq", question: "Solve: 3(x + 2) = 15", options: ["x = 3", "x = 5", "x = 7", "x = 1"], correctAnswer: "x = 3", hint: "Expand first, or divide by 3" },
      { id: generateId(), type: "input", question: "Solve: 7x + 3 = 5x + 11", correctAnswer: "4", hint: "Subtract 5x and 3 from both sides" },
      { id: generateId(), type: "mcq", question: "Solve: 2(x - 3) = 4x - 10", options: ["x = 2", "x = -2", "x = 4", "x = 8"], correctAnswer: "x = 2", hint: "Expand, then solve" },
      { id: generateId(), type: "input", question: "Solve: 9x - 6 = 3x + 18", correctAnswer: "4", hint: "Subtract 3x and add 6" },
      { id: generateId(), type: "mcq", question: "Solve: 4(2x + 1) = 28", options: ["x = 3", "x = 6", "x = 3.5", "x = 7"], correctAnswer: "x = 3", hint: "Expand or divide both sides by 4" },
      { id: generateId(), type: "input", question: "Solve: 5x + 8 = 2x + 23", correctAnswer: "5", hint: "Isolate x terms on left" },
      { id: generateId(), type: "mcq", question: "Solve: 3x - 7 = x + 5", options: ["x = 6", "x = 12", "x = -6", "x = 1"], correctAnswer: "x = 6", hint: "Subtract x and add 7" },
    ],
  },
  {
    id: "swyk-1",
    number: "SWYK #1",
    title: "Boss Fight: Equations",
    description: "Test your equation solving skills!",
    type: "boss",
    xpReward: 100,
    timeLimit: 180,
    questions: [
      { id: generateId(), type: "input", question: "Solve: 5x + 12 = 3x + 28", correctAnswer: "8", hint: "No hints in boss fights!" },
      { id: generateId(), type: "input", question: "Solve: 4(x + 3) = 2(x + 9)", correctAnswer: "3", hint: "" },
      { id: generateId(), type: "input", question: "Expand and simplify: 3(2x - 1) + 4(x + 2)", correctAnswer: "10x + 5", hint: "" },
      { id: generateId(), type: "mcq", question: "Solve: 7x - 5 = 4x + 13", options: ["x = 6", "x = 8", "x = 4", "x = 2"], correctAnswer: "x = 6", hint: "" },
      { id: generateId(), type: "input", question: "Solve: 2(3x + 4) = 5x + 15", correctAnswer: "7", hint: "" },
      { id: generateId(), type: "mcq", question: "Simplify: 6x - 2(x + 3) + 4", options: ["4x - 2", "4x + 2", "8x + 2", "4x - 10"], correctAnswer: "4x - 2", hint: "" },
      { id: generateId(), type: "input", question: "Solve: 8x + 7 = 3x + 32", correctAnswer: "5", hint: "" },
      { id: generateId(), type: "input", question: "Solve: 3(2x - 5) = 4x + 1", correctAnswer: "8", hint: "" },
    ],
  },
  {
    id: "1.03",
    number: "1.03",
    title: "Equations with Fractions",
    description: "Clear denominators and solve equations with fractions",
    type: "lesson",
    xpReward: 70,
    badge: "fraction-fragger",
    questions: [
      { id: generateId(), type: "input", question: "Solve: x/2 + 3 = 7", correctAnswer: "8", hint: "Subtract 3, then multiply by 2" },
      { id: generateId(), type: "mcq", question: "Solve: x/3 = 5", options: ["x = 15", "x = 8", "x = 5/3", "x = 2"], correctAnswer: "x = 15", hint: "Multiply both sides by 3" },
      { id: generateId(), type: "input", question: "Solve: 2x/5 = 6", correctAnswer: "15", hint: "Multiply both sides by 5, then divide by 2" },
      { id: generateId(), type: "mcq", question: "Solve: (x + 2)/4 = 3", options: ["x = 10", "x = 14", "x = 1", "x = 12"], correctAnswer: "x = 10", hint: "Multiply by 4, then subtract 2" },
      { id: generateId(), type: "input", question: "Solve: x/4 - 2 = 5", correctAnswer: "28", hint: "Add 2, then multiply by 4" },
      { id: generateId(), type: "mcq", question: "Solve: 3x/4 = 9", options: ["x = 12", "x = 6", "x = 27/4", "x = 3"], correctAnswer: "x = 12", hint: "Multiply by 4, divide by 3" },
      { id: generateId(), type: "input", question: "Solve: (x - 1)/3 = 4", correctAnswer: "13", hint: "Multiply by 3, then add 1" },
      { id: generateId(), type: "mcq", question: "Solve: x/6 + 1 = 5", options: ["x = 24", "x = 4", "x = 30", "x = 36"], correctAnswer: "x = 24", hint: "Subtract 1, then multiply by 6" },
      { id: generateId(), type: "input", question: "Solve: 5x/2 = 20", correctAnswer: "8", hint: "Multiply by 2, divide by 5" },
      { id: generateId(), type: "mcq", question: "Solve: (2x + 1)/5 = 3", options: ["x = 7", "x = 8", "x = 14", "x = 2"], correctAnswer: "x = 7", hint: "Multiply by 5, subtract 1, divide by 2" },
      { id: generateId(), type: "input", question: "Solve: x/2 + x/4 = 6", correctAnswer: "8", hint: "Find common denominator, combine" },
      { id: generateId(), type: "mcq", question: "Solve: (x + 5)/2 = x - 1", options: ["x = 7", "x = 3", "x = 5", "x = -7"], correctAnswer: "x = 7", hint: "Multiply by 2 and solve" },
    ],
  },
  {
    id: "1.04",
    number: "1.04",
    title: "Graphing Linear Equations",
    description: "Identify slope, y-intercept, and match graphs to equations",
    type: "lesson",
    xpReward: 70,
    badge: "graphing-guru",
    questions: [
      { id: generateId(), type: "mcq", question: "What is the slope of y = 3x + 2?", options: ["3", "2", "-3", "1/3"], correctAnswer: "3", hint: "In y = mx + b, m is the slope" },
      { id: generateId(), type: "mcq", question: "What is the y-intercept of y = -2x + 5?", options: ["5", "-2", "2", "-5"], correctAnswer: "5", hint: "In y = mx + b, b is the y-intercept" },
      { id: generateId(), type: "input", question: "Find the slope of y = 4x - 7", correctAnswer: "4", hint: "Look at the coefficient of x" },
      { id: generateId(), type: "mcq", question: "Which line passes through (0, 3)?", options: ["y = 2x + 3", "y = 3x + 2", "y = x - 3", "y = 2x - 3"], correctAnswer: "y = 2x + 3", hint: "Y-intercept is the y-value when x = 0" },
      { id: generateId(), type: "input", question: "Find the y-intercept of y = -5x + 8", correctAnswer: "8", hint: "The constant term is the y-intercept" },
      { id: generateId(), type: "mcq", question: "A line with slope 0 is:", options: ["Horizontal", "Vertical", "Diagonal", "Undefined"], correctAnswer: "Horizontal", hint: "No rise means flat line" },
      { id: generateId(), type: "mcq", question: "Which equation has a negative slope?", options: ["y = -3x + 1", "y = 3x - 1", "y = 3x + 1", "y = x + 3"], correctAnswer: "y = -3x + 1", hint: "Negative slope means line goes down left to right" },
      { id: generateId(), type: "input", question: "If a line has m = 2 and b = -4, write y = mx + b", correctAnswer: "y = 2x - 4", hint: "Substitute m and b into the formula" },
      { id: generateId(), type: "mcq", question: "Find the slope between (1, 2) and (3, 8)", options: ["3", "2", "5", "6"], correctAnswer: "3", hint: "Slope = (y2 - y1)/(x2 - x1)" },
      { id: generateId(), type: "mcq", question: "Which line is steeper?", options: ["y = 5x + 1", "y = 2x + 3", "y = x + 5", "y = 0.5x + 2"], correctAnswer: "y = 5x + 1", hint: "Larger absolute slope = steeper" },
      { id: generateId(), type: "input", question: "Find slope between (0, 1) and (2, 5)", correctAnswer: "2", hint: "Rise over run" },
      { id: generateId(), type: "mcq", question: "y = 7 represents:", options: ["Horizontal line at y = 7", "Vertical line at x = 7", "Line through origin", "Slope of 7"], correctAnswer: "Horizontal line at y = 7", hint: "No x term means horizontal" },
    ],
  },
  {
    id: "1.05",
    number: "1.05",
    title: "Standard Form",
    description: "Convert between forms and find intercepts",
    type: "lesson",
    xpReward: 70,
    badge: "slope-master",
    questions: [
      { id: generateId(), type: "mcq", question: "Convert y = 2x + 4 to standard form", options: ["2x - y = -4", "-2x + y = 4", "2x + y = 4", "x - 2y = 4"], correctAnswer: "2x - y = -4", hint: "Move terms to get Ax + By = C" },
      { id: generateId(), type: "input", question: "Find the x-intercept of 3x + y = 9", correctAnswer: "3", hint: "Set y = 0 and solve for x" },
      { id: generateId(), type: "input", question: "Find the y-intercept of 2x + y = 6", correctAnswer: "6", hint: "Set x = 0 and solve for y" },
      { id: generateId(), type: "mcq", question: "Convert y = -x + 5 to standard form", options: ["x + y = 5", "x - y = 5", "-x + y = 5", "x + y = -5"], correctAnswer: "x + y = 5", hint: "Add x to both sides" },
      { id: generateId(), type: "input", question: "Find x-intercept of x + 2y = 8", correctAnswer: "8", hint: "Let y = 0" },
      { id: generateId(), type: "mcq", question: "What is standard form?", options: ["Ax + By = C", "y = mx + b", "y - y1 = m(x - x1)", "x = a"], correctAnswer: "Ax + By = C", hint: "Standard form has x and y on same side" },
      { id: generateId(), type: "input", question: "Find y-intercept of 4x - y = -8", correctAnswer: "8", hint: "Set x = 0, solve for y" },
      { id: generateId(), type: "mcq", question: "Convert y = 3x - 6 to standard form", options: ["3x - y = 6", "-3x + y = -6", "3x + y = 6", "y - 3x = 6"], correctAnswer: "3x - y = 6", hint: "Subtract y and add 6" },
      { id: generateId(), type: "input", question: "Find x-intercept of 5x + 2y = 10", correctAnswer: "2", hint: "Set y = 0" },
      { id: generateId(), type: "mcq", question: "Which is in standard form?", options: ["4x + 3y = 12", "y = 4x + 3", "3y = 4x + 12", "x = 4y - 3"], correctAnswer: "4x + 3y = 12", hint: "Both variables on left, constant on right" },
      { id: generateId(), type: "input", question: "Find y-intercept of x - 3y = 12", correctAnswer: "-4", hint: "Set x = 0, solve for y" },
      { id: generateId(), type: "mcq", question: "Convert 2x - 3y = 6 to slope-intercept", options: ["y = (2/3)x - 2", "y = (2/3)x + 2", "y = (3/2)x - 2", "y = -(2/3)x - 2"], correctAnswer: "y = (2/3)x - 2", hint: "Solve for y" },
    ],
  },
  {
    id: "swyk-2",
    number: "SWYK #2",
    title: "Boss Fight: Graphing & Standard Form",
    description: "Prove your graphing mastery!",
    type: "boss",
    xpReward: 120,
    timeLimit: 180,
    questions: [
      { id: generateId(), type: "input", question: "Find the slope of y = -7x + 3", correctAnswer: "-7", hint: "" },
      { id: generateId(), type: "input", question: "Find the x-intercept of 4x + 2y = 16", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "mcq", question: "Convert y = 5x - 3 to standard form", options: ["5x - y = 3", "-5x + y = -3", "5x + y = 3", "y - 5x = 3"], correctAnswer: "5x - y = 3", hint: "" },
      { id: generateId(), type: "input", question: "Find y-intercept of 3x - 2y = 10", correctAnswer: "-5", hint: "" },
      { id: generateId(), type: "mcq", question: "Find slope between (2, 3) and (6, 11)", options: ["2", "4", "8", "1"], correctAnswer: "2", hint: "" },
      { id: generateId(), type: "input", question: "Find slope of 4x + 2y = 10 (as decimal)", correctAnswer: "-2", hint: "" },
      { id: generateId(), type: "mcq", question: "Which line has y-intercept of -3?", options: ["y = 2x - 3", "y = -3x + 2", "y = 3x + 2", "y = 2x + 3"], correctAnswer: "y = 2x - 3", hint: "" },
      { id: generateId(), type: "input", question: "Find x-intercept of y = 2x - 6", correctAnswer: "3", hint: "" },
    ],
  },
  {
    id: "1.06",
    number: "1.06",
    title: "Parallel & Perpendicular Lines",
    description: "Understand relationship between slopes of parallel and perpendicular lines",
    type: "lesson",
    xpReward: 80,
    badge: "parallel-pro",
    questions: [
      { id: generateId(), type: "mcq", question: "Parallel lines have:", options: ["Same slope", "Opposite slopes", "Negative reciprocal slopes", "No slope"], correctAnswer: "Same slope", hint: "Parallel means they never meet" },
      { id: generateId(), type: "mcq", question: "Perpendicular lines have slopes that are:", options: ["Negative reciprocals", "Equal", "Opposite", "Zero"], correctAnswer: "Negative reciprocals", hint: "Flip and negate" },
      { id: generateId(), type: "input", question: "Line has slope 3. Parallel line slope is:", correctAnswer: "3", hint: "Parallel = same slope" },
      { id: generateId(), type: "input", question: "Line has slope 2. Perpendicular slope is:", correctAnswer: "-1/2", hint: "Flip 2 to 1/2, then negate" },
      { id: generateId(), type: "mcq", question: "Which is parallel to y = 4x - 1?", options: ["y = 4x + 7", "y = -4x + 1", "y = (1/4)x - 1", "y = -(1/4)x + 2"], correctAnswer: "y = 4x + 7", hint: "Same slope (4)" },
      { id: generateId(), type: "mcq", question: "Which is perpendicular to y = 2x + 3?", options: ["y = -(1/2)x + 1", "y = 2x - 3", "y = -2x + 3", "y = (1/2)x + 3"], correctAnswer: "y = -(1/2)x + 1", hint: "Negative reciprocal of 2" },
      { id: generateId(), type: "input", question: "Slope perpendicular to m = -4:", correctAnswer: "1/4", hint: "Flip -4 to -1/4, then negate" },
      { id: generateId(), type: "mcq", question: "Are y = 3x + 1 and y = 3x - 5 parallel?", options: ["Yes", "No", "Perpendicular", "Same line"], correctAnswer: "Yes", hint: "Both have slope 3" },
      { id: generateId(), type: "input", question: "Slope parallel to m = -2/3:", correctAnswer: "-2/3", hint: "Parallel = same slope" },
      { id: generateId(), type: "mcq", question: "Are y = 2x + 1 and y = -0.5x + 3 perpendicular?", options: ["Yes", "No", "Parallel", "Same line"], correctAnswer: "Yes", hint: "2 and -1/2 are negative reciprocals" },
      { id: generateId(), type: "input", question: "Perpendicular to m = 1/5:", correctAnswer: "-5", hint: "Flip and negate" },
      { id: generateId(), type: "mcq", question: "Find equation parallel to y = -x + 4 through (0, 2)", options: ["y = -x + 2", "y = x + 2", "y = -x + 4", "y = -x - 2"], correctAnswer: "y = -x + 2", hint: "Same slope -1, y-int is 2" },
    ],
  },
  {
    id: "1.07",
    number: "1.07",
    title: "Equation Given Two Points",
    description: "Find the equation of a line given two points",
    type: "lesson",
    xpReward: 80,
    badge: "two-point-titan",
    questions: [
      { id: generateId(), type: "input", question: "Find slope between (1, 2) and (3, 6)", correctAnswer: "2", hint: "m = (y2-y1)/(x2-x1)" },
      { id: generateId(), type: "mcq", question: "Equation through (0, 4) with slope 2", options: ["y = 2x + 4", "y = 4x + 2", "y = 2x - 4", "y = -2x + 4"], correctAnswer: "y = 2x + 4", hint: "Use y = mx + b with m = 2, b = 4" },
      { id: generateId(), type: "input", question: "Find slope between (2, 1) and (4, 7)", correctAnswer: "3", hint: "Rise over run" },
      { id: generateId(), type: "mcq", question: "Line through (1, 5) and (2, 8) has slope:", options: ["3", "5", "2", "8"], correctAnswer: "3", hint: "m = (8-5)/(2-1)" },
      { id: generateId(), type: "input", question: "Find slope between (0, 0) and (5, 10)", correctAnswer: "2", hint: "10/5 = ?" },
      { id: generateId(), type: "mcq", question: "Equation through (0, -3) with m = 4", options: ["y = 4x - 3", "y = -3x + 4", "y = 4x + 3", "y = -4x - 3"], correctAnswer: "y = 4x - 3", hint: "b = -3 is y-intercept" },
      { id: generateId(), type: "input", question: "Slope between (3, 2) and (7, 10)", correctAnswer: "2", hint: "(10-2)/(7-3)" },
      { id: generateId(), type: "mcq", question: "Line through (0, 0) and (2, 6) is:", options: ["y = 3x", "y = 2x", "y = 6x", "y = x"], correctAnswer: "y = 3x", hint: "Slope = 6/2, passes through origin" },
      { id: generateId(), type: "input", question: "Write equation: m = 5, passes through (0, 1)", correctAnswer: "y = 5x + 1", hint: "Use y = mx + b" },
      { id: generateId(), type: "mcq", question: "Points (2, 3) and (2, 7) form:", options: ["Vertical line", "Horizontal line", "Slope of 2", "Slope of 4"], correctAnswer: "Vertical line", hint: "Same x-value" },
      { id: generateId(), type: "input", question: "Slope between (-1, 4) and (3, 0)", correctAnswer: "-1", hint: "(0-4)/(3-(-1))" },
      { id: generateId(), type: "mcq", question: "Through (1, 1) and (3, 5), find b", options: ["b = -1", "b = 1", "b = 0", "b = 2"], correctAnswer: "b = -1", hint: "m = 2, use y = mx + b with point" },
    ],
  },
  {
    id: "1.08",
    number: "1.08",
    title: "Word Problems with Lines",
    description: "Apply linear equations to real-world problems",
    type: "lesson",
    xpReward: 80,
    questions: [
      { id: generateId(), type: "mcq", question: "A taxi charges $3 base + $2/km. What's the equation?", options: ["C = 2k + 3", "C = 3k + 2", "C = 5k", "C = 2k - 3"], correctAnswer: "C = 2k + 3", hint: "Start fee + rate per km" },
      { id: generateId(), type: "input", question: "Phone plan: $20/month + $0.10/text. Cost for 50 texts:", correctAnswer: "25", hint: "20 + 0.10(50)" },
      { id: generateId(), type: "mcq", question: "Pool drains at 5L/min from 200L. Equation:", options: ["V = 200 - 5t", "V = 5t + 200", "V = 200t - 5", "V = 5t - 200"], correctAnswer: "V = 200 - 5t", hint: "Starts at 200, decreases by 5 each min" },
      { id: generateId(), type: "input", question: "Plumber: $50 call-out + $25/hour. 3 hours cost:", correctAnswer: "125", hint: "50 + 25(3)" },
      { id: generateId(), type: "mcq", question: "Candle 12 inches burns 0.5 in/hr. Height after 4 hrs:", options: ["10 inches", "8 inches", "6 inches", "11 inches"], correctAnswer: "10 inches", hint: "12 - 0.5(4)" },
      { id: generateId(), type: "input", question: "Car rental: $40/day + $0.20/km. 100km in 2 days:", correctAnswer: "100", hint: "40(2) + 0.20(100)" },
      { id: generateId(), type: "mcq", question: "Salary $500/week + $50/sale. 8 sales earns:", options: ["$900", "$800", "$400", "$550"], correctAnswer: "$900", hint: "500 + 50(8)" },
      { id: generateId(), type: "input", question: "Movie ticket $12, popcorn $5. 4 tickets + 2 popcorns:", correctAnswer: "58", hint: "12(4) + 5(2)" },
      { id: generateId(), type: "mcq", question: "Line perpendicular to road with slope 3:", options: ["Slope -1/3", "Slope 3", "Slope -3", "Slope 1/3"], correctAnswer: "Slope -1/3", hint: "Perpendicular = negative reciprocal" },
      { id: generateId(), type: "input", question: "Gym: $100 sign-up + $30/month. 6 months cost:", correctAnswer: "280", hint: "100 + 30(6)" },
      { id: generateId(), type: "mcq", question: "Parallel fence to y = 2x + 1 has slope:", options: ["2", "-2", "1/2", "-1/2"], correctAnswer: "2", hint: "Parallel = same slope" },
      { id: generateId(), type: "input", question: "Water tank fills 8L/min. Start 20L. After 5 min:", correctAnswer: "60", hint: "20 + 8(5)" },
    ],
  },
  {
    id: "swyk-3",
    number: "SWYK #3",
    title: "Boss Fight: Lines & Applications",
    description: "Master parallel, perpendicular, and word problems!",
    type: "boss",
    xpReward: 140,
    timeLimit: 240,
    questions: [
      { id: generateId(), type: "input", question: "Perpendicular slope to m = 5:", correctAnswer: "-1/5", hint: "" },
      { id: generateId(), type: "input", question: "Slope through (2, 4) and (6, 12)", correctAnswer: "2", hint: "" },
      { id: generateId(), type: "mcq", question: "Car rental $50/day + $0.15/mile. 200 miles in 3 days:", options: ["$180", "$200", "$150", "$165"], correctAnswer: "$180", hint: "" },
      { id: generateId(), type: "input", question: "Parallel slope to m = -3/4:", correctAnswer: "-3/4", hint: "" },
      { id: generateId(), type: "mcq", question: "Line through (0, 5) with slope -2:", options: ["y = -2x + 5", "y = 2x + 5", "y = -2x - 5", "y = 5x - 2"], correctAnswer: "y = -2x + 5", hint: "" },
      { id: generateId(), type: "input", question: "Perpendicular slope to m = -1/3:", correctAnswer: "3", hint: "" },
      { id: generateId(), type: "mcq", question: "Which is parallel to 2x + y = 4?", options: ["2x + y = 10", "x + 2y = 4", "2x - y = 4", "-2x + y = 4"], correctAnswer: "2x + y = 10", hint: "" },
      { id: generateId(), type: "input", question: "Plumber $75 call + $40/hr. 4 hours cost:", correctAnswer: "235", hint: "" },
    ],
  },
  {
    id: "1.09",
    number: "1.09",
    title: "Substitution Method",
    description: "Solve systems of equations using substitution",
    type: "lesson",
    xpReward: 90,
    badge: "substitution-samurai",
    questions: [
      { id: generateId(), type: "input", question: "y = 2x, x + y = 9. Find x:", correctAnswer: "3", hint: "Substitute y = 2x into second equation" },
      { id: generateId(), type: "mcq", question: "y = x + 1, 2x + y = 10. Find x:", options: ["x = 3", "x = 4", "x = 2", "x = 5"], correctAnswer: "x = 3", hint: "2x + (x+1) = 10" },
      { id: generateId(), type: "input", question: "y = 3x, x + y = 8. Find y:", correctAnswer: "6", hint: "Find x first, then y = 3x" },
      { id: generateId(), type: "mcq", question: "x = 4, 2x + 3y = 14. Find y:", options: ["y = 2", "y = 6", "y = 4", "y = 3"], correctAnswer: "y = 2", hint: "2(4) + 3y = 14" },
      { id: generateId(), type: "input", question: "y = x - 2, x + y = 10. Find x:", correctAnswer: "6", hint: "x + (x-2) = 10" },
      { id: generateId(), type: "mcq", question: "y = 2x + 1, 3x + y = 11. Find x:", options: ["x = 2", "x = 3", "x = 4", "x = 1"], correctAnswer: "x = 2", hint: "3x + (2x+1) = 11" },
      { id: generateId(), type: "input", question: "y = 5 - x, 2x + y = 8. Find x:", correctAnswer: "3", hint: "2x + (5-x) = 8" },
      { id: generateId(), type: "mcq", question: "x = 2y, 3x - y = 10. Find y:", options: ["y = 2", "y = 4", "y = 3", "y = 5"], correctAnswer: "y = 2", hint: "3(2y) - y = 10" },
      { id: generateId(), type: "input", question: "y = x + 4, 2x - y = 2. Find x:", correctAnswer: "6", hint: "2x - (x+4) = 2" },
      { id: generateId(), type: "mcq", question: "y = 3, x + 2y = 11. Find x:", options: ["x = 5", "x = 8", "x = 3", "x = 6"], correctAnswer: "x = 5", hint: "x + 2(3) = 11" },
      { id: generateId(), type: "input", question: "y = 2x - 1, x + y = 5. Find x:", correctAnswer: "2", hint: "x + (2x-1) = 5" },
      { id: generateId(), type: "mcq", question: "x = y + 3, 2x + y = 12. Find y:", options: ["y = 2", "y = 3", "y = 4", "y = 6"], correctAnswer: "y = 2", hint: "2(y+3) + y = 12" },
    ],
  },
  {
    id: "1.10",
    number: "1.10",
    title: "Elimination & Matrices Intro",
    description: "Solve systems using elimination and intro to matrices",
    type: "lesson",
    xpReward: 100,
    badge: "elimination-elite",
    questions: [
      { id: generateId(), type: "input", question: "x + y = 5, x - y = 1. Find x:", correctAnswer: "3", hint: "Add equations to eliminate y" },
      { id: generateId(), type: "mcq", question: "2x + y = 7, x + y = 4. Find x:", options: ["x = 3", "x = 2", "x = 4", "x = 1"], correctAnswer: "x = 3", hint: "Subtract equations" },
      { id: generateId(), type: "input", question: "x + 2y = 8, x - 2y = 0. Find x:", correctAnswer: "4", hint: "Add to eliminate y" },
      { id: generateId(), type: "mcq", question: "3x + y = 10, x + y = 6. Find x:", options: ["x = 2", "x = 4", "x = 3", "x = 1"], correctAnswer: "x = 2", hint: "Subtract second from first" },
      { id: generateId(), type: "input", question: "2x + 3y = 12, 2x + y = 8. Find y:", correctAnswer: "2", hint: "Subtract to eliminate x" },
      { id: generateId(), type: "mcq", question: "x + y = 7, 2x - y = 5. Find x:", options: ["x = 4", "x = 3", "x = 5", "x = 2"], correctAnswer: "x = 4", hint: "Add equations" },
      { id: generateId(), type: "input", question: "3x + 2y = 13, x + 2y = 7. Find x:", correctAnswer: "3", hint: "Subtract second from first" },
      { id: generateId(), type: "mcq", question: "Matrix [2 3] + [1 4] = ?", options: ["[3 7]", "[3 1]", "[2 12]", "[1 7]"], correctAnswer: "[3 7]", hint: "Add corresponding elements" },
      { id: generateId(), type: "input", question: "2x - y = 5, x + y = 7. Find y:", correctAnswer: "3", hint: "Add to get 3x = 12, then find y" },
      { id: generateId(), type: "mcq", question: "Matrix 2 × [3 1] = ?", options: ["[6 2]", "[5 3]", "[6 1]", "[3 2]"], correctAnswer: "[6 2]", hint: "Multiply each element by 2" },
      { id: generateId(), type: "input", question: "4x + y = 13, 2x + y = 7. Find x:", correctAnswer: "3", hint: "Subtract second from first" },
      { id: generateId(), type: "mcq", question: "[1 2] + [3 1] = ?", options: ["[4 3]", "[4 2]", "[3 3]", "[2 3]"], correctAnswer: "[4 3]", hint: "1+3 and 2+1" },
    ],
  },
  {
    id: "swyk-4",
    number: "SWYK #4",
    title: "Boss Fight: Systems of Equations",
    description: "Master substitution and elimination!",
    type: "boss",
    xpReward: 150,
    timeLimit: 240,
    questions: [
      { id: generateId(), type: "input", question: "y = 3x, x + y = 16. Find x:", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "input", question: "x + y = 10, x - y = 2. Find x:", correctAnswer: "6", hint: "" },
      { id: generateId(), type: "mcq", question: "2x + y = 11, x + y = 7. Find x:", options: ["x = 4", "x = 3", "x = 5", "x = 2"], correctAnswer: "x = 4", hint: "" },
      { id: generateId(), type: "input", question: "y = x + 2, 2x + y = 14. Find x:", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "mcq", question: "Matrix [5 2] - [2 1] = ?", options: ["[3 1]", "[7 3]", "[3 3]", "[7 1]"], correctAnswer: "[3 1]", hint: "" },
      { id: generateId(), type: "input", question: "3x + 2y = 16, x + 2y = 8. Find x:", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "mcq", question: "3 × [2 4] = ?", options: ["[6 12]", "[5 7]", "[6 4]", "[2 12]"], correctAnswer: "[6 12]", hint: "" },
      { id: generateId(), type: "input", question: "x = 2y, 3x + y = 14. Find y:", correctAnswer: "2", hint: "" },
    ],
  },
  {
    id: "review",
    number: "Review",
    title: "Unit Review",
    description: "Practice all concepts from the unit",
    type: "review",
    xpReward: 100,
    questions: [
      { id: generateId(), type: "mcq", question: "Expand: 4(2x - 3)", options: ["8x - 12", "8x - 3", "6x - 7", "8x + 12"], correctAnswer: "8x - 12", hint: "Multiply each term by 4" },
      { id: generateId(), type: "input", question: "Solve: 5x - 3 = 2x + 9", correctAnswer: "4", hint: "Get x terms together" },
      { id: generateId(), type: "mcq", question: "Slope of y = -4x + 7", options: ["-4", "7", "4", "-7"], correctAnswer: "-4", hint: "Coefficient of x" },
      { id: generateId(), type: "input", question: "x-intercept of 2x + y = 8", correctAnswer: "4", hint: "Set y = 0" },
      { id: generateId(), type: "mcq", question: "Perpendicular slope to m = 1/2", options: ["-2", "2", "1/2", "-1/2"], correctAnswer: "-2", hint: "Flip and negate" },
      { id: generateId(), type: "input", question: "Slope between (1, 3) and (5, 11)", correctAnswer: "2", hint: "Rise over run" },
      { id: generateId(), type: "mcq", question: "y = 2x, x + y = 6. Find x:", options: ["2", "3", "4", "1"], correctAnswer: "2", hint: "Substitute" },
      { id: generateId(), type: "input", question: "x + y = 9, x - y = 3. Find x:", correctAnswer: "6", hint: "Add equations" },
      { id: generateId(), type: "mcq", question: "Parallel slope to m = 5", options: ["5", "-5", "1/5", "-1/5"], correctAnswer: "5", hint: "Same slope" },
      { id: generateId(), type: "input", question: "Solve: x/3 + 2 = 6", correctAnswer: "12", hint: "Subtract 2, multiply by 3" },
    ],
  },
  {
    id: "final-test",
    number: "Final",
    title: "Final Boss: Unit Test",
    description: "The ultimate challenge - prove your mastery!",
    type: "test",
    xpReward: 300,
    badge: "legend-of-lines",
    timeLimit: 600,
    questions: [
      { id: generateId(), type: "input", question: "Expand: 3(4x - 5)", correctAnswer: "12x - 15", hint: "" },
      { id: generateId(), type: "mcq", question: "Simplify: 7x - 2 + 3x + 8", options: ["10x + 6", "4x + 6", "10x - 6", "4x - 6"], correctAnswer: "10x + 6", hint: "" },
      { id: generateId(), type: "input", question: "Solve: 4x + 7 = 3x + 12", correctAnswer: "5", hint: "" },
      { id: generateId(), type: "mcq", question: "Solve: 2(x + 3) = 14", options: ["x = 4", "x = 7", "x = 5.5", "x = 8"], correctAnswer: "x = 4", hint: "" },
      { id: generateId(), type: "input", question: "Solve: x/4 - 3 = 2", correctAnswer: "20", hint: "" },
      { id: generateId(), type: "mcq", question: "Slope of y = -3x + 8", options: ["-3", "8", "3", "-8"], correctAnswer: "-3", hint: "" },
      { id: generateId(), type: "input", question: "y-intercept of 3x + y = 12", correctAnswer: "12", hint: "" },
      { id: generateId(), type: "mcq", question: "x-intercept of 4x + 2y = 20", options: ["5", "10", "4", "20"], correctAnswer: "5", hint: "" },
      { id: generateId(), type: "input", question: "Slope between (2, 5) and (6, 13)", correctAnswer: "2", hint: "" },
      { id: generateId(), type: "mcq", question: "Perpendicular slope to m = -3", options: ["1/3", "-1/3", "3", "-3"], correctAnswer: "1/3", hint: "" },
      { id: generateId(), type: "input", question: "Parallel slope to m = 7", correctAnswer: "7", hint: "" },
      { id: generateId(), type: "mcq", question: "Line through (0, -2) with slope 3", options: ["y = 3x - 2", "y = -2x + 3", "y = 3x + 2", "y = -3x - 2"], correctAnswer: "y = 3x - 2", hint: "" },
      { id: generateId(), type: "input", question: "y = 4x, x + y = 10. Find x:", correctAnswer: "2", hint: "" },
      { id: generateId(), type: "mcq", question: "x + y = 8, x - y = 2. Find y:", options: ["3", "5", "4", "6"], correctAnswer: "3", hint: "" },
      { id: generateId(), type: "input", question: "2x + y = 9, x + y = 5. Find x:", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "mcq", question: "Matrix [4 1] + [2 5] = ?", options: ["[6 6]", "[6 5]", "[4 6]", "[2 6]"], correctAnswer: "[6 6]", hint: "" },
      { id: generateId(), type: "input", question: "Convert y = 2x + 6 to Ax + By = C (answer A):", correctAnswer: "2", hint: "" },
      { id: generateId(), type: "mcq", question: "Which is steeper: y = 2x or y = 5x?", options: ["y = 5x", "y = 2x", "Same", "Cannot tell"], correctAnswer: "y = 5x", hint: "" },
      { id: generateId(), type: "input", question: "Solve: 6x - 4 = 2x + 12", correctAnswer: "4", hint: "" },
      { id: generateId(), type: "mcq", question: "Plumber $60 call + $35/hr. 2 hours:", options: ["$130", "$95", "$120", "$70"], correctAnswer: "$130", hint: "" },
    ],
  },
];

export function getLevelById(id: string): Level | undefined {
  return LEVELS.find(l => l.id === id);
}

export function getNextLevel(currentId: string): Level | undefined {
  const index = LEVELS.findIndex(l => l.id === currentId);
  if (index >= 0 && index < LEVELS.length - 1) {
    return LEVELS[index + 1];
  }
  return undefined;
}

export function isLevelUnlocked(levelId: string, completedLevels: string[]): boolean {
  const levelIndex = LEVELS.findIndex(l => l.id === levelId);
  if (levelIndex === 0) return true;
  const previousLevel = LEVELS[levelIndex - 1];
  return completedLevels.includes(previousLevel.id);
}
